version: '3.8'

services:
  database:
    image: mysql:8.0-debian
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: m2z-design

volumes:
  database: