version: '3.8'

services:
  database:
    image: mysql:8.0-debian
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: m2z-design

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '3305:80'
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3306

volumes:
  database: